# Applies to all jobs, can be overridden in each
default:
    image:
        # Image from dockerhub per default. Specify full path to use a different image.
        name: alexpovel/latex
        # Override any entrypoint back to a naked shell so that job `script`s can be
        # executed normally.
        # See also: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image
        # Cannot use `make` as ENTRYPOINT even if all scripts used it: runner expects an
        # entrypoint that accepts shell scripts ("the runner expects that the image has
        # no entrypoint or that the entrypoint is prepared to start a shell command. ")
        # See also:
        # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image
        entrypoint: [ "" ]
    # LaTeX and pandoc stages both provide PDFs:
    artifacts:
        # artifacts.zip is renamed to current tag/branch:
        name: "$CI_COMMIT_REF_NAME"
        paths:
            # Return all found *.pdf-files using wildcard.
            # For example, a thesis and the accompanying presentation.
            - "*.pdf"
    # Run job 'only' if it fulfills certain criteria (BETTER: use `rules`):
    # only:
        # - tags
    before_script:
    # Make sure to clean any PDFs that might have crept in via the cache, forcing a
    # remake at least once (otherwise, no remake might occur).
    # It would be better to exclude the PDFs from the cache in the first place. This is
    # not available yet, see: https://gitlab.com/gitlab-org/gitlab/-/issues/220017#note_440142507
      - make clean-pdf

preflight:
    stage: .pre
    script:
        - make preflight
    # Preflight checks are relevant, but we are interested in how exactly later jobs
    # error out if preflight fails. Therefore, allow failure.
    allow_failure: true
    inherit:
        # Do not inherit artifacts, this stage has none.
        default: [image]

build_latex:
    stage: build
    script:
        - make tex
    cache:
      untracked: true
      key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

build_pandoc:
    stage: build
    script:
        - make README.pdf
